# Generated by Django 3.2.5 on 2021-07-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0002_delete_abc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('pin', models.IntegerField(max_length=10)),
                ('cardname', models.CharField(max_length=20)),
                ('cardnum', models.IntegerField(max_length=16)),
                ('expmon', models.DateField(max_length=10)),
                ('expyr', models.DateField(max_length=4)),
                ('cvv', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('pin', models.IntegerField(max_length=10)),
            ],
        ),
    ]
