# Generated by Django 3.2.5 on 2021-07-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0004_auto_20210720_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Users',
        ),
    ]
