# Generated by Django 3.2.5 on 2021-07-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0005_rename_person_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expmon',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='expyr',
            field=models.CharField(max_length=4),
        ),
    ]
