# Generated by Django 3.2.5 on 2021-07-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0006_auto_20210721_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cod',
            new_name='Cash',
        ),
    ]
