# Generated by Django 3.2.5 on 2021-07-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0008_auto_20210729_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cash',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
