# Generated by Django 3.2.5 on 2021-07-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0009_auto_20210731_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
