# Generated by Django 3.2.5 on 2021-07-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0011_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
