# Generated by Django 3.2.5 on 2021-07-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk', '0012_alter_home_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('price', models.IntegerField()),
                ('addcart', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('price', models.IntegerField()),
                ('addcart', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('price', models.IntegerField()),
                ('addcart', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('price', models.IntegerField()),
                ('addcart', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sneak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('price', models.IntegerField()),
                ('addcart', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='images')),
                ('price', models.IntegerField()),
                ('addcart', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
